=== giacomotelloli/domoticOS/xml/variables.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema   xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	  <xsd:element name="variabili">
		  <xsd:complexType>
		  <xsd:sequence>
            <xsd:element ref="variabile" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
		  </xsd:complexType>
	</xsd:element>

	<xsd:element name="variabile" >
		<xsd:complexType>
        <xsd:sequence>
            <xsd:element ref="valoreStato" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element ref="unitaMisura" minOccurs="0" maxOccurs="1"/>
      </xsd:sequence> 
        
          <xsd:attribute name="nome" type="xsd:string" use="required"/>
          <xsd:attribute name="valoreMax" type="xsd:string" use="optional"/>
          <xsd:attribute name="valoreMin" type="xsd:string" use="optional"/>
		</xsd:complexType>
	</xsd:element >

	 <xsd:element name="unitaMisura" type="xsd:string"></xsd:element>
<xsd:element name="valoreStato" type="xsd:string"></xsd:element>
   
</xsd:schema>

=== giacomotelloli/domoticOS/xml_popolato/cucina/frigorifero/frigorifero_variables.xml
<?xml version="1.0" encoding="UTF-8"?>
<variabili  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../variables.xsd"> 
	
		<variabile nome="temperatura_frigo"  valoreMin="-16" valoreMax="25">
      <unitaMisura>gradi</unitaMisura>
    </variabile>
		
		<variabile nome="temperatura_freezer" valoreMax="6" valoreMin="-20">
		   <unitaMisura>gradi</unitaMisura>
		 </variabile>
		 
		<variabile nome="presenza_ghiaccio" >
		   <valoreStato>si</valoreStato>
		   <valoreStato>no</valoreStato>
		</variabile>
		
		<variabile nome="capienza_frigo" valoreMax="100" valoreMin="0" >
		  <unitaMisura>kg</unitaMisura>
		</variabile>
				
    	<variabile nome="quantita_triglie"  valoreMax="100" valoreMin="0">
<unitaMisura>kg</unitaMisura>
		</variabile>


    	<variabile nome="quantita_trote"  valoreMax="100" valoreMin="0">
    	<unitaMisura>kg</unitaMisura>
		</variabile>
		
    	<variabile nome="quantita_carote" valoreMax="100" valoreMin="0">
    	<unitaMisura>kg</unitaMisura>
		</variabile>

	
    	<variabile nome="quantita_mele" valoreMax="100" valoreMin="0">
    	<unitaMisura>kg</unitaMisura>
		</variabile>
		
		
    	<variabile nome="quantita_prociutto_cotto" valoreMax="100" valoreMin="0">
    	<unitaMisura>kg</unitaMisura>
		</variabile>

    	<variabile nome="quantita_formaggio_di_capra" valoreMax="100" valoreMin="0">
    	<unitaMisura>kg</unitaMisura>
		</variabile>


</variabili>

=== giacomotelloli/domoticOS/xml_popolato/cameretta/computer/computer_variables.xml
<?xml version="1.0" encoding="UTF-8"?>
<variabili xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../variables.xsd">
<variabile nome="stato_accensione"><valoreStato>acceso</valoreStato><valoreStato>spento</valoreStato></variabile>
<variabile nome="temperatura_cpu" valoreMax="50" valoreMin="0"><unitaMisura>gradi</unitaMisura></variabile>
<variabile nome="ram_occupata" valoreMax="100" valoreMin="0"><unitaMisura>%</unitaMisura></variabile>
<variabile nome="disco_occupato" valoreMax="100" valoreMin="0"><unitaMisura>%</unitaMisura></variabile>
<variabile nome="sistema_operativo"><valoreStato>Arch Linux</valoreStato><valoreStato>Ubuntu</valoreStato><valoreStato>Mandriva</valoreStato><valoreStato>Windows 98</valoreStato></variabile>
<variabile nome="antivirus">
<valoreStato>Kaspersky</valoreStato>
<valoreStato>AVG</valoreStato>
</variabile>
</variabili>

=== giacomotelloli/domoticOS/xml/giardino/serra/serra_variables.xml
<?xml version="1.0" encoding="UTF-8"?>
<variabili  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../variables.xsd"> 
	
		
		<variabile nome="umidita_ambiente" valoreMax="100" valoreMin="0">
		   <unitaMisura>%</unitaMisura>
		</variabile>

  <variabile nome="stato_irrigazione" valoreMax="100" valoreMin="0">
		   <valoreStato>accesa</valoreStato>
		   <valoreStato>spenta</valoreStato>
		</variabile>
				
		
<variabile nome="media_umidita_pomodori" valoreMax="100" valoreMin="0">
		   <unitaMisura>g/m^3</unitaMisura>
		</variabile>
						
<variabile nome="media_umidita_broccoletti" valoreMax="100" valoreMin="0">
		   <unitaMisura>g/m^3</unitaMisura>
		</variabile>
				
				<variabile nome="media_umidita_patate" valoreMax="100" valoreMin="0">
		   <unitaMisura>g/m^3</unitaMisura>
		</variabile>
				
<variabile nome="media_umidita_cavoli" valoreMax="100" valoreMin="0">
		   <unitaMisura>g/m^3</unitaMisura>
  </variabile>
				
    

</variabili>

=== giacomotelloli/domoticOS/xml_popolato/garage/macchina/macchina_variables.xml
<?xml version="1.0" encoding="UTF-8"?>
<variabili  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../variables.xsd"> 
	
		<variabile nome="km_percorsi"  valoreMin="0" valoreMax="900000">
      <unitaMisura>km</unitaMisura>
    </variabile>
		
		<variabile nome="carica_batteria" valoreMax="100" valoreMin="0">
		   <unitaMisura>%</unitaMisura>
		 </variabile>
		 
		<variabile nome="pressione_gommaAS"  valoreMax="3" valoreMin="0">
		    <unitaMisura>bar</unitaMisura>
		</variabile>
		
<variabile nome="pressione_gommaAD"  valoreMax="3" valoreMin="0">
		    <unitaMisura>bar</unitaMisura>
		</variabile>

		<variabile nome="pressione_gommaPS"  valoreMax="3" valoreMin="0">
		    <unitaMisura>bar</unitaMisura>
		</variabile>
		
<variabile nome="pressione_gommaPD"  valoreMax="3" valoreMin="0">
		    <unitaMisura>bar</unitaMisura>
		</variabile>
		
		<variabile nome="livello_serbatoio" valoreMax="100" valoreMin="0">
		   <unitaMisura>%</unitaMisura>
		</variabile>
				

    	<variabile nome="stato_blocco">
      <valoreStato>aperta</valoreStato>
      <valoreStato>chiusa</valoreStato>
		</variabile>
				
				
    	<variabile nome="stato_accensione">
      <valoreStato>accesa</valoreStato>
      <valoreStato>spenta</valoreStato>
		</variabile>
				
<variabile nome="stato_tracking">
      <valoreStato>attivo</valoreStato>
      <valoreStato>disattivato</valoreStato>
		</variabile>
				
      
    	<variabile nome="latitudine" valoreMax="90" valoreMin="-90">
  <unitaMisura>DD</unitaMisura>
		</variabile>
		
		<variabile nome="longitudine" valoreMax="180" valoreMin="-180">
    <unitaMisura>DD</unitaMisura>
		</variabile>
				
				

</variabili>

=== giacomotelloli/domoticOS/xml_popolato/cucina/macchinetta_caffe/macchinetta_caffe_variables.xml
<?xml version="1.0" encoding="UTF-8"?>
<variabili  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../variables.xsd"> 
	
		
		<variabile nome="livello_acqua" valoreMax="50" valoreMin="0">
		   <unitaMisura>cl</unitaMisura>
		</variabile>
				
  <variabile nome="stato_cialda">
      <valoreStato>inserita</valoreStato>
      <valoreStato>non inserita</valoreStato>
		</variabile>
				
    <variabile nome="temperatura_macchinetta" valoreMax="40" valoreMin="0">
      <unitaMisura>gradi</unitaMisura>
    </variabile>
    	<variabile nome="stato_accensione">
      <valoreStato>accesa</valoreStato>
      <valoreStato>spenta</valoreStato>
		</variabile>
				
<variabile nome="stato_erogazione">
      <valoreStato>in corso</valoreStato>
      <valoreStato>finita</valoreStato>
		</variabile>
				
				

</variabili>
