=== giacomotelloli/domoticOS/xml_popolato/status.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema   xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	  <xsd:element name="stati">
		  <xsd:complexType>
		  <xsd:sequence>
            <xsd:element ref="stato" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
		  </xsd:complexType>
	</xsd:element>

	<xsd:element name="stato" >
		<xsd:complexType>
          <xsd:sequence>
          <xsd:element ref="varOsservata" minOccurs="1"   maxOccurs="unbounded"></xsd:element>
          </xsd:sequence>

          <xsd:attribute name="timestamp" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element >

	  <xsd:element  name="varOsservata">
      <xsd:complexType>
        <xsd:sequence>
          <xsd:element ref="valore" />
        </xsd:sequence>
       <xsd:attribute name="nome" type="xsd:string" use="required"/>
		    </xsd:complexType>
    </xsd:element>

    <xsd:element name="valore" type="xsd:string"></xsd:element>
</xsd:schema>

=== giacomotelloli/domoticOS/xml/giardino/serra/serra_status.xml
<?xml version="1.0" encoding="UTF-8"?>
<stati xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../status.xsd"> 
	<stato timestamp="19-06-2020-15-06-51">
		<varOsservata nome="umidita_ambiente"><valore>30</valore></varOsservata>
		<varOsservata nome="accensione_irrigazione"><valore>accesa</valore></varOsservata>
		<varOsservata nome="media_umidita_pomodori"><valore>50</valore></varOsservata>
		<varOsservata nome="media_umidita_patate"><valore>20</valore></varOsservata>
    <varOsservata nome="mediaumidita_cavoli"><valore>30</valore></varOsservata>
	</stato>
<stato timestamp="19-06-2020-19-06-51">
		<varOsservata nome="umidita_ambiente"><valore>30</valore></varOsservata>
		<varOsservata nome="accensione_irrigazione"><valore>accesa</valore></varOsservata>
		<varOsservata nome="media_umidita_pomodori"><valore>50</valore></varOsservata>
		<varOsservata nome="media_umidita_patate"><valore>20</valore></varOsservata>
    <varOsservata nome="media_umidita_cavoli"><valore>30</valore></varOsservata>
    <varOsservata nome="media_umidita_broccoletti"><valore>12</valore></varOsservata>
	</stato>
</stati>

=== giacomotelloli/domoticOS/xml/cucina/frigorifero/frigorifero_status.xml
<?xml version="1.0" encoding="UTF-8"?>
<stati xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../status.xsd"> 
	
	<stato timestamp="19-06-2020-15-06-51">
		<varOsservata nome="temperatura_frigo"><valore>20</valore></varOsservata>
		<varOsservata nome="temperatura_freezer"><valore>-10</valore></varOsservata>
		<varOsservata nome="presenza_ghiaccio"><valore>si</valore></varOsservata>
    <varOsservata nome="capienza_frigo"><valore>73</valore></varOsservata>
    <varOsservata nome="quantita_triglie"><valore>3</valore></varOsservata>
    <varOsservata nome="quantita_trote"><valore>3</valore></varOsservata>
    <varOsservata nome="quantita_carote"><valore>3</valore></varOsservata>
    <varOsservata nome="quantita_mele"><valore>50</valore></varOsservata>
    <varOsservata nome="quantita_prociutto_cotto"><valore>6</valore></varOsservata>
    <varOsservata nome="quantita_formaggio_di_capra"><valore>8</valore></varOsservata>
	</stato>

<stato timestamp="19-06-2020-19-06-51">
		<varOsservata nome="temperatura_frigo"><valore>21</valore></varOsservata>
		<varOsservata nome="temperatura_freezer"><valore>-14</valore> </varOsservata>
		<varOsservata nome="presenza_ghiaccio"><valore>no</valore></varOsservata>
    <varOsservata nome="capienza_frigo"><valore>75</valore></varOsservata>
    <varOsservata nome="quantita_triglie"><valore>5</valore></varOsservata>
    <varOsservata nome="quantita_trote"><valore>3</valore></varOsservata>
    <varOsservata nome="quantita_carote"><valore>3</valore></varOsservata>
    <varOsservata nome="quantita_mele"><valore>50</valore></varOsservata>
    <varOsservata nome="quantita_prociutto_cotto"><valore>6</valore></varOsservata>
    <varOsservata nome="quantita_formaggio_di_capra"><valore>8</valore></varOsservata>
</stato>
</stati>

=== giacomotelloli/domoticOS/xml/cucina/macchinetta_caffe/macchinetta_caffe_status.xml
<?xml version="1.0" encoding="UTF-8"?>
<stati xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../status.xsd"><stato timestamp="19-06-2020-15-06-51"><varOsservata nome="stato_accensione"><valore>accesa</valore></varOsservata><varOsservata nome="temperatura_macchinetta"><valore>15</valore></varOsservata><varOsservata nome="livello_acqua"><valore>50</valore></varOsservata><varOsservata nome="stato_erogazione"><valore>in corso</valore></varOsservata><varOsservata nome="stato_cialda"><valore>inserita</valore></varOsservata></stato><stato timestamp="19-06-2020-19-06-51"><varOsservata nome="stato_accensione"><valore>spenta</valore></varOsservata><varOsservata nome="temperatura_macchinetta"><valore>10</valore></varOsservata><varOsservata nome="livello_acqua"><valore>8</valore></varOsservata><varOsservata nome="stato_erogazione"><valore>finita</valore></varOsservata><varOsservata nome="stato_cialda"><valore>non inserita</valore></varOsservata></stato><stato timestamp="18-9-2020-14-59-13"><varOsservata nome="stato_accensione"><valore>spenta</valore></varOsservata><varOsservata nome="temperatura_macchinetta"><valore>10</valore></varOsservata><varOsservata nome="livello_acqua"><valore>8</valore></varOsservata><varOsservata nome="stato_erogazione"><valore>finita</valore></varOsservata><varOsservata nome="stato_cialda"><valore>non inserita</valore></varOsservata></stato><stato timestamp="18-9-2020-14-59-59"><varOsservata nome="stato_accensione"><valore>spenta</valore></varOsservata><varOsservata nome="temperatura_macchinetta"><valore>10</valore></varOsservata><varOsservata nome="livello_acqua"><valore>8</valore></varOsservata><varOsservata nome="stato_erogazione"><valore>finita</valore></varOsservata><varOsservata nome="stato_cialda"><valore>non inserita</valore></varOsservata></stato><stato timestamp="18-9-2020-15-00-04"><varOsservata nome="stato_accensione"><valore>spenta</valore></varOsservata><varOsservata nome="temperatura_macchinetta"><valore>10</valore></varOsservata><varOsservata nome="livello_acqua"><valore>8</valore></varOsservata><varOsservata nome="stato_erogazione"><valore>finita</valore></varOsservata><varOsservata nome="stato_cialda"><valore>non inserita</valore></varOsservata></stato><stato timestamp="18-9-2020-15-00-08"><varOsservata nome="stato_accensione"><valore>spenta</valore></varOsservata><varOsservata nome="temperatura_macchinetta"><valore>10</valore></varOsservata><varOsservata nome="livello_acqua"><valore>8</valore></varOsservata><varOsservata nome="stato_erogazione"><valore>finita</valore></varOsservata><varOsservata nome="stato_cialda"><valore>non inserita</valore></varOsservata></stato><stato timestamp="18-9-2020-15-00-37"><varOsservata nome="stato_accensione"><valore>spenta</valore></varOsservata><varOsservata nome="temperatura_macchinetta"><valore>10</valore></varOsservata><varOsservata nome="livello_acqua"><valore>8</valore></varOsservata><varOsservata nome="stato_erogazione"><valore>finita</valore></varOsservata><varOsservata nome="stato_cialda"><valore>non inserita</valore></varOsservata></stato><stato timestamp="18-9-2020-15-00-41"><varOsservata nome="stato_accensione"><valore>spenta</valore></varOsservata><varOsservata nome="temperatura_macchinetta"><valore>5</valore></varOsservata><varOsservata nome="livello_acqua"><valore>8</valore></varOsservata><varOsservata nome="stato_erogazione"><valore>finita</valore></varOsservata><varOsservata nome="stato_cialda"><valore>non inserita</valore></varOsservata></stato><stato timestamp="18-9-2020-15-11-21"><varOsservata nome="stato_accensione"><valore>spenta</valore></varOsservata><varOsservata nome="temperatura_macchinetta"><valore>5</valore></varOsservata><varOsservata nome="livello_acqua"><valore>8</valore></varOsservata><varOsservata nome="stato_erogazione"><valore>finita</valore></varOsservata><varOsservata nome="stato_cialda"><valore>non inserita</valore></varOsservata></stato><stato timestamp="18-9-2020-15-12-43"><varOsservata nome="stato_accensione"><valore>spenta</valore></varOsservata><varOsservata nome="temperatura_macchinetta"><valore>5</valore></varOsservata><varOsservata nome="livello_acqua"><valore>8</valore></varOsservata><varOsservata nome="stato_erogazione"><valore>finita</valore></varOsservata><varOsservata nome="stato_cialda"><valore>non inserita</valore></varOsservata></stato><stato timestamp="18-9-2020-15-15-15"><varOsservata nome="stato_accensione"><valore>spenta</valore></varOsservata><varOsservata nome="temperatura_macchinetta"><valore>0</valore></varOsservata><varOsservata nome="livello_acqua"><valore>8</valore></varOsservata><varOsservata nome="stato_erogazione"><valore>finita</valore></varOsservata><varOsservata nome="stato_cialda"><valore>non inserita</valore></varOsservata></stato><stato timestamp="18-9-2020-16-36-21"><varOsservata nome="stato_accensione"><valore>spenta</valore></varOsservata><varOsservata nome="temperatura_macchinetta"><valore>0</valore></varOsservata><varOsservata nome="livello_acqua"><valore>8</valore></varOsservata><varOsservata nome="stato_erogazione"><valore>finita</valore></varOsservata><varOsservata nome="stato_cialda"><valore>non inserita</valore></varOsservata></stato><stato timestamp="18-9-2020-16-39-15"><varOsservata nome="stato_accensione"><valore>spenta</valore></varOsservata><varOsservata nome="temperatura_macchinetta"><valore>0</valore></varOsservata><varOsservata nome="livello_acqua"><valore>8</valore></varOsservata><varOsservata nome="stato_erogazione"><valore>finita</valore></varOsservata><varOsservata nome="stato_cialda"><valore>non inserita</valore></varOsservata></stato></stati>

=== giacomotelloli/domoticOS/xml_popolato/garage/macchina/macchina_status.xml
<?xml version="1.0" encoding="UTF-8"?>
<stati xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../status.xsd"> 
	<stato timestamp="19-06-2020-15-06-51">
		<varOsservata nome="km_percorsi"><valore>17200</valore></varOsservata>
		<varOsservata nome="carica_batteria"><valore>95</valore> </varOsservata>
		<varOsservata nome="pressione_gommaAS"><valore>3</valore> </varOsservata>
    <varOsservata nome="pressione_gommaAD"><valore>3</valore> </varOsservata>
    <varOsservata nome="pressione_gommaPS"><valore>3</valore> </varOsservata>
    <varOsservata nome="pressione_gommaPD"><valore>3</valore> </varOsservata>
    <varOsservata nome="livello_serbatoio"><valore>50</valore> </varOsservata>
    <varOsservata nome="stato_blocco"><valore>chiusa</valore></varOsservata>
    <varOsservata nome="stato_accensione"><valore>accesa</valore></varOsservata>
    <varOsservata nome="stato_tracking"><valore>attivo</valore></varOsservata>
	  <varOsservata  nome="latitudine"><valore>41.405981</valore></varOsservata>
	  <varOsservata  nome="longitudine"><valore>13.047585</valore></varOsservata>
	  
	</stato>

<stato timestamp="19-06-2020-19-06-51">
		<varOsservata nome="km_percorsi"><valore>30300</valore></varOsservata>
		<varOsservata nome="carica_batteria"><valore>80</valore></varOsservata>
		<varOsservata nome="pressione_gommaAS"><valore>3</valore></varOsservata>
    <varOsservata nome="pressione_gommaAD"><valore>3</valore></varOsservata>
    <varOsservata nome="pressione_gommaPS"><valore>3</valore></varOsservata>
    <varOsservata nome="pressione_gommaPD"><valore>1.56</valore></varOsservata>
    <varOsservata nome="livello_serbatoio"><valore>10</valore></varOsservata>
    <varOsservata nome="stato_blocco"><valore>aperta</valore></varOsservata>
    <varOsservata nome="stato_accensione"><valore>spenta</valore></varOsservata>
    <varOsservata nome="stato_tracking"><valore>disattivato</valore></varOsservata>
</stato>

</stati>
